name: Monitor citas

on:
  schedule:
    # Cada 30 min los primeros 10 días del mes
    - cron: "*/30 * 1-10 * *"
    # Cada 2 horas del 11 al 26
    - cron: "0 */2 11-26 * *"
    # Cada 30 min del 27 al 31
    - cron: "*/30 * 27-31 * *"
  workflow_dispatch: # permite lanzarlo manualmente también

jobs:
  monitor:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{ secrets.NODE_ENV }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
      HEADLESS: ${{ secrets.HEADLESS }}
      MONITOR_URL: ${{ secrets.MONITOR_URL }}
      TARGET_DATA: ${{ secrets.TARGET_DATA }}
      MAILER_SERVICE: ${{ secrets.MAILER_SERVICE }}
      MAILER_USER: ${{ secrets.MAILER_USER }}
      MAILER_PASS: ${{ secrets.MAILER_PASS }}
      MAILER_FROM: ${{ secrets.MAILER_FROM }}
      MAILER_TO: ${{ secrets.MAILER_TO }}
      MAILER_CC: ${{ secrets.MAILER_CC }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm" # Cachea node_modules automáticamente

      - name: Get Playwright version
        id: playwright-version
        run: echo "version=$(node -p "require('./package-lock.json').packages['node_modules/@playwright/test'].version")" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: playwright-${{ runner.os }}-${{ steps.playwright-version.outputs.version }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      
      - name: Install Playwright system dependencies (Only with cache)
        if: steps.playwright-cache.outputs.cache-hit == 'true'
        run: npx playwright install-deps

      - name: Run monitor script
        run: |
          export NODE_ENV=production
          export HEADLESS=true
          mkdir -p records/logs
          mkdir -p records/states/data
          mkdir -p records/screenshots
          echo "---------------- $(date) ----------------" >> records/logs/cron.log
          node src/monitor.js >> records/logs/cron.log 2>&1

      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: records/logs/

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: records/screenshots/

      - name: Upload states
        uses: actions/upload-artifact@v4
        with:
          name: states
          path: records/states/

      - name: Upload data
        uses: actions/upload-artifact@v4
        with:
          name: data
          path: records/states/data/
